// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729143533_AddFechaIngresoToEmpleado")]
    partial class AddFechaIngresoToEmpleado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("backend.Models.Empleado", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("backend.Models.NominaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Afp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CedulaSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CorreoEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CuotaCumpleanos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailDestinatario")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEnvioCorreo")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Incentivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Isr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreEmpleadoSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NominaPeriodoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Prestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Reembolso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeguroMedico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeguroVehiculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sfs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoPeriodo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDevengado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NominaPeriodoId");

                    b.ToTable("NominaDetalles");
                });

            modelBuilder.Entity("backend.Models.NominaPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaProcesado")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontoTotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalDevengado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quincena")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NominaPeriodos");
                });

            modelBuilder.Entity("backend.Models.NominaDetalle", b =>
                {
                    b.HasOne("backend.Models.NominaPeriodo", "NominaPeriodo")
                        .WithMany("Detalles")
                        .HasForeignKey("NominaPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NominaPeriodo");
                });

            modelBuilder.Entity("backend.Models.NominaPeriodo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
