// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.ConfiguracionSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("SmtpEnableSsl")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SmtpPassword")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpSenderEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SmtpSenderName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SmtpServer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SmtpUsername")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Configuraciones");
                });

            modelBuilder.Entity("backend.Models.Empleado", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Puesto")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("Codigo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("backend.Models.NominaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Afp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CedulaSnapshot")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("CorreoEnviado")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("CuotaCumpleanos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EmailDestinatario")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("FechaEnvioCorreo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Incentivo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Isr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreEmpleadoSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("NominaPeriodoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Reembolso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeguroMedico")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SeguroVehiculo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sfs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoPeriodo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDevengado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NominaPeriodoId");

                    b.ToTable("NominaDetalles");
                });

            modelBuilder.Entity("backend.Models.NominaPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaProcesado")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotalDeducciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalDevengado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quincena")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("NominaPeriodos");
                });

            modelBuilder.Entity("backend.Models.NominaDetalle", b =>
                {
                    b.HasOne("backend.Models.NominaPeriodo", "NominaPeriodo")
                        .WithMany("Detalles")
                        .HasForeignKey("NominaPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NominaPeriodo");
                });

            modelBuilder.Entity("backend.Models.NominaPeriodo", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
